=== aleenamv575/cat/emsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<ems:schema xmlns:ems="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/empSchema" xmlns:tns="http://www.example.org/emsSchema" elementFormDefault="qualified">
<ems:element name="Company">
	<ems:complexType>
		<ems:sequence>
			<ems:element name="Employee" maxOccurs="unbounded">
				<ems:complexType>
					<ems:sequence>
						<ems:element name="Emp-ID" type="ems:integer"/>
						<ems:element name="Emp-name" type="ems:string"/>
						<ems:element name="Emp-age" type="ems:integer"/>
						<ems:element name="Emp-salary">
							<ems:simpleType>
								<ems:restriction base="ems:integer">
									<ems:minInclusive value="50000"/>
									<ems:maxInclusive value="200000"/>
								</ems:restriction>
							</ems:simpleType>
						</ems:element>
						<ems:element name="Emp-emailid" type="ems:string"/>
						<ems:element name="Emp-phonenum" type="ems:integer"/>
						<ems:element name="Emp-designation" type="ems:string"/>
					</ems:sequence>
				</ems:complexType>
			</ems:element>
		</ems:sequence>
	</ems:complexType>
	<ems:unique name="emp_ID">
  		<ems:selector xpath="ems:id"/>
  		<ems:field xpath="@EmployeeID"/>
 	</ems:unique>
</ems:element>
</ems:schema>

=== aleenamv575/cat/employee.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="empstylesheet.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="emsSchema.xsd">
  <Employee >
    <Emp-ID>1</Emp-ID>
    <Emp-name>Aleena</Emp-name>
    <Emp-age>34</Emp-age>
    <Emp-salary>60000</Emp-salary>
    <Emp-emailid>jack@gmail.com</Emp-emailid>
    <Emp-phonenum>496826381</Emp-phonenum>
    <Emp-designation>Tester</Emp-designation>
  </Employee>
  <Employee>
    <Emp-ID>2</Emp-ID>
    <Emp-name>Nitin</Emp-name>
    <Emp-age>28</Emp-age>
    <Emp-salary>90000</Emp-salary>
    <Emp-emailid>jill@gmail.com</Emp-emailid>
    <Emp-phonenum>997625732</Emp-phonenum>
    <Emp-designation>Developer</Emp-designation>
  </Employee>
  <Employee>
    <Emp-ID>3</Emp-ID>
    <Emp-name>James</Emp-name>
    <Emp-age>45</Emp-age>
    <Emp-salary>120000</Emp-salary>
    <Emp-emailid>james@gmail.com</Emp-emailid>
    <Emp-phonenum>993876428</Emp-phonenum>
    <Emp-designation>Manager</Emp-designation>
  </Employee>
  <Employee>
    <Emp-ID>4</Emp-ID>
    <Emp-name>Julie</Emp-name>
    <Emp-age>55</Emp-age>
    <Emp-salary>180000</Emp-salary>
    <Emp-emailid>julie@gmail.com</Emp-emailid>
    <Emp-phonenum>897346283</Emp-phonenum>
    <Emp-designation>Project head</Emp-designation>
  </Employee>
  <Employee>
    <Emp-ID>5</Emp-ID>
    <Emp-name>Jay</Emp-name>
    <Emp-age>47</Emp-age>
    <Emp-salary>100000</Emp-salary>
    <Emp-emailid>jayjay@gmail.com</Emp-emailid>
    <Emp-phonenum>9023782392</Emp-phonenum>
    <Emp-designation>Admin</Emp-designation>
  </Employee>
</Company>
